#
# Cosmological parameters
#
Omega_m : 0.3
Omega_v : 0.7
sigma_8 : 0.82355
n_spec : 0.97
w0 : -1.0
wa : 0.0
omb : 0.048
h0 : 0.69
#
# Survey and galaxy parameters
#
# area in degrees
# n_gal,lens_n_gal in gals/arcmin^2
area : 2000.0
sourcephotoz : multihisto
lensphotoz : multihisto
source_tomobins : 9
lens_tomobins : 9
sigma_e : 0.39441348451
shear_REDSHIFT_FILE : zdistris/mean_roman_nzmin_normalized_sc1bd4.nz
clustering_REDSHIFT_FILE : zdistris/mean_roman_nzmin_normalized_sc1bd4.nz
# DHFS METHOD 1 START - from Eq 15 in 2004.04702
#source_n_gal : 5.1,5.1,5.1,5.1,5.1,5.1,5.1,5.1,5.1
#lens_n_gal : 5.1,5.1,5.1,5.1,5.1,5.1,5.1,5.1,5.1
# DHFS METHOD 1 END
# DHFS METHOD 2 START - fraction from the unormalized mean_roman_nz_sc1bd4.nz | fi = ∫n_i(z) dz => n_gal = fi/∑_{i=1}^9 fi
source_n_gal : 0.11127596,0.11135324,0.11135334,0.11135333,0.11135334,0.11135334,0.11135287,0.11117724,0.10942736
lens_n_gal : 0.11127596,0.11135324,0.11135334,0.11135333,0.11135334,0.11135334,0.11135287,0.11117724,0.10942736
# DHFS METHOD 2 END
# DHFS - gbias from table 2 in 2004.04702 (Galaxy bias (tomographic bins))
lens_tomogbias : 1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.1
lens_tomo_bmag : 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
# IA parameters
IA : 1
A_ia : 0.0
eta_ia : 0.0
#
# Covariance paramters
#
# tmin,tmax in arcminutes - DHFS values from cocoa/Cocoa/projects/roman_real/data/example1.dataset
tmin : 2.5
tmax : 250.0
ntheta : 15
ng : 0
cng : 0
outdir : output/out_cov_roman_sc1bd4/
filename : cov_roman_sc1bd4
ss : true
ls : true
ll : true
